<script setup>
import { ref } from 'vue'

const email = ref('')
const isLoading = ref(false)
const errorMessage = ref('')
const successMessage = ref('')

async function handleSubmit() {
  if (!email.value) {
    errorMessage.value = 'Please enter your email address.'
    return
  }

  isLoading.value = true
  errorMessage.value = ''
  successMessage.value = ''

  console.log('Initiating forgot-password request for email:', email.value)

  try {
    const response = await fetch(
      'http://127.0.0.1:8000/resetlogin',
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          email: email.value
        }),
      }
    )

    console.log('Response received. Status:', response.status)
    const data = await response.json()
    console.log('Response body data:', data)

    if (!response.ok) {
      console.error(`Forgot-password request failed with status ${response.status}:`, data)
      errorMessage.value = data.detail || 'Failed to send reset link. Please check your email.'
      return
    }

    successMessage.value = 'Reset email sent successfully'

  } catch (error) {
    console.error('Network error or exception during forgot-password request:', error)
    errorMessage.value = 'A network error occurred. Please check your connection and try again.'
  } finally {
    isLoading.value = false
  }
}
</script>

<template>
  <section class="forgot-page">
    <!-- Left Panel: Branding -->
    <div class="forgot-branding">
      <!-- Decorative Markdown Watermark -->
      <div class="md-watermark" aria-hidden="true">
        <pre class="md-text">
# llms.txt

> A proposal to standardize
> how websites communicate
> with large language models.

## Overview

llms.txt is a file that
provides structured info
about your site for LLMs.

## Usage

```bash
$ llms-gen https://example.com
```

### Output Format

- title: Site Name
- description: A brief...
- sections:
  - /docs
  - /api
  - /blog

## Why llms.txt?

AI models need structured,
curated content to provide
accurate, helpful responses.

---

```markdown
# Example Output
> Generated by llms.txt
> generator v1.0
```

## Getting Started

1. Enter your site URL
2. Configure options
3. Generate your file
4. Deploy to your root

---

© 2026 llms.txt generator
        </pre>
      </div>

      <div class="branding-content">
        <h1 class="branding-title">
          LLMS.txt <span class="branding-accent">generator</span>
        </h1>
        <p class="branding-tagline">Generate text using LLMs</p>

        <!-- Decorative lines -->
        <div class="branding-lines">
          <div class="b-line"></div>
          <div class="b-line"></div>
          <div class="b-line"></div>
        </div>

        <p class="branding-description">
          Reset password to recover access to<br />
          generating structured llms.txt files.
        </p>
      </div>
    </div>

    <!-- Right Panel: Forgot Password Form -->
    <div class="forgot-form-panel">
      <div class="forgot-form-container">
        <div class="form-header">
          <h2 class="form-title">Reset password</h2>
          <p class="form-subtitle">Enter your email and we'll send you a link to reset your password</p>
        </div>

        <!-- Error Message Display -->
        <div v-if="errorMessage" class="error-banner" role="alert">
          <svg class="error-icon" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="12" cy="12" r="10"></circle>
            <line x1="12" y1="8" x2="12" y2="12"></line>
            <line x1="12" y1="16" x2="12.01" y2="16"></line>
          </svg>
          <span class="error-text">{{ errorMessage }}</span>
        </div>

        <!-- Success Message Display -->
        <div v-if="successMessage" class="success-banner" role="status">
          <svg class="success-icon" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
            <polyline points="22 4 12 14.01 9 11.01"></polyline>
          </svg>
          <span class="success-text">{{ successMessage }}</span>
        </div>

        <form v-if="!successMessage" class="forgot-form" @submit.prevent="handleSubmit">
          <!-- Email Field -->
          <div class="input-group">
            <label class="input-label" for="forgot-email">Email Address</label>
            <div class="input-wrapper">
              <svg class="input-icon" width="18" height="18" viewBox="0 0 24 24" fill="none">
                <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M22 6l-10 7L2 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
              <input
                id="forgot-email"
                v-model="email"
                type="email"
                placeholder="you@example.com"
                required
                autocomplete="email"
              />
            </div>
          </div>

          <!-- Submit Button -->
          <button
            type="submit"
            class="submit-btn"
            :class="{ 'submit-btn--loading': isLoading }"
            :disabled="isLoading"
          >
            <span v-if="!isLoading">Send reset link</span>
            <span v-else class="spinner"></span>
          </button>
        </form>

        <div class="form-footer">
          <p>Remember your password? <router-link to="/login" class="login-link">Back to sign in</router-link></p>
        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>
/* ===== Page Layout ===== */
.forgot-page {
  min-height: 100vh;
  display: flex;
  font-family: 'Inter', 'Segoe UI', sans-serif;
}

/* ===== Left Branding Panel ===== */
.forgot-branding {
  flex: 1;
  background: #000000;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 48px;
  position: relative;
  overflow: hidden;
}

.forgot-branding::before {
  content: '';
  position: absolute;
  top: -50%;
  right: -30%;
  width: 80%;
  height: 200%;
  background: linear-gradient(
    135deg,
    rgba(255, 255, 255, 0.02) 0%,
    rgba(255, 255, 255, 0.05) 50%,
    transparent 100%
  );
  transform: rotate(-12deg);
  pointer-events: none;
}

/* ===== Markdown Watermark Overlay ===== */
.md-watermark {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 0;
  pointer-events: none;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
}

.md-text {
  font-family: 'SF Mono', 'Fira Code', 'Cascadia Code', 'Consolas', monospace;
  font-size: 0.72rem;
  line-height: 1.8;
  color: rgba(255, 255, 255, 0.12);
  white-space: pre;
  margin: 0;
  padding: 40px;
  transform: rotate(-4deg) scale(1.15);
  user-select: none;
  letter-spacing: 0.3px;
  animation:
    md-drift 25s ease-in-out infinite alternate,
    md-pulse 8s ease-in-out infinite;
}

@keyframes md-drift {
  0% {
    transform: rotate(-4deg) scale(1.15) translateY(0px);
  }
  100% {
    transform: rotate(-4deg) scale(1.15) translateY(-30px);
  }
}

@keyframes md-pulse {
  0%, 100% { opacity: 0.5; }
  30% { opacity: 1; }
  60% { opacity: 0.35; }
  80% { opacity: 0.9; }
}

.branding-content {
  position: relative;
  z-index: 1;
  max-width: 400px;
}

.branding-title {
  font-size: 2.8rem;
  font-weight: 300;
  color: #ffffff;
  letter-spacing: -0.5px;
  margin: 0 0 8px 0;
}

.branding-accent {
  font-weight: 700;
  font-style: italic;
}

.branding-tagline {
  font-size: 1rem;
  font-style: italic;
  color: rgba(255, 255, 255, 0.5);
  margin: 0 0 32px 0;
}

.branding-lines {
  display: flex;
  flex-direction: column;
  gap: 10px;
  margin-bottom: 28px;
}

.b-line {
  height: 1px;
  background: linear-gradient(
    90deg,
    rgba(255, 255, 255, 0.25) 0%,
    rgba(255, 255, 255, 0.08) 100%
  );
}

.b-line:nth-child(1) { width: 100%; }
.b-line:nth-child(2) { width: 75%; }
.b-line:nth-child(3) { width: 50%; }

.branding-description {
  font-size: 0.95rem;
  color: rgba(255, 255, 255, 0.45);
  line-height: 1.7;
  margin: 0;
}

/* ===== Right Form Panel ===== */
.forgot-form-panel {
  flex: 1;
  background: #ffffff;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 48px;
}

.forgot-form-container {
  width: 100%;
  max-width: 380px;
}

.form-header {
  margin-bottom: 36px;
}

/* ===== Error Banner ===== */
.error-banner {
  display: flex;
  align-items: center;
  gap: 10px;
  background-color: #fdf2f2;
  color: #de350b;
  border: 1px solid #f8b4b4;
  padding: 12px 16px;
  border-radius: 8px;
  font-size: 0.88rem;
  margin-bottom: 20px;
  text-align: left;
  animation: fadeIn 0.35s ease-in-out;
}

.error-icon {
  flex-shrink: 0;
  color: #de350b;
}

.error-text {
  font-weight: 500;
  line-height: 1.4;
}

/* ===== Success Banner ===== */
.success-banner {
  display: flex;
  align-items: center;
  gap: 10px;
  background-color: #f3faf5;
  color: #00875a;
  border: 1px solid #abf5d1;
  padding: 12px 16px;
  border-radius: 8px;
  font-size: 0.88rem;
  margin-bottom: 20px;
  text-align: left;
  animation: fadeIn 0.35s ease-in-out;
}

.success-icon {
  flex-shrink: 0;
  color: #00875a;
}

.success-text {
  font-weight: 500;
  line-height: 1.4;
}

@keyframes fadeIn {
  from { opacity: 0; transform: translateY(-4px); }
  to { opacity: 1; transform: translateY(0); }
}

.form-title {
  font-size: 1.75rem;
  font-weight: 700;
  color: #111111;
  margin: 0 0 6px 0;
}

.form-subtitle {
  font-size: 0.95rem;
  color: #888888;
  margin: 0;
}

/* ===== Developer Helper Box ===== */
.dev-link-helper {
  background: #f4f5f7;
  border: 1px solid #dfe1e6;
  border-left: 4px solid #0052cc;
  padding: 16px;
  border-radius: 8px;
  margin-bottom: 24px;
  text-align: left;
}

.dev-label {
  font-weight: bold;
  color: #0747a6;
  font-size: 0.9rem;
  margin: 0 0 4px 0;
}

.dev-text {
  color: #505f79;
  font-size: 0.85rem;
  margin: 0 0 12px 0;
}

.dev-link {
  display: inline-block;
  background: #0052cc;
  color: white;
  padding: 8px 14px;
  border-radius: 6px;
  font-size: 0.85rem;
  font-weight: 600;
  text-decoration: none;
  transition: background 0.25s;
}

.dev-link:hover {
  background: #0747a6;
}

/* ===== Form ===== */
.forgot-form {
  display: flex;
  flex-direction: column;
  gap: 22px;
}

/* ===== Input Group ===== */
.input-group {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.input-label {
  font-size: 0.85rem;
  font-weight: 600;
  color: #333333;
  letter-spacing: 0.2px;
}

.input-wrapper {
  display: flex;
  align-items: center;
  border: 1px solid #e0e0e0;
  border-radius: 10px;
  padding: 0 14px;
  background: #fafafa;
  transition: all 0.25s ease;
}

.input-wrapper:focus-within {
  border-color: #111111;
  background: #ffffff;
  box-shadow: 0 0 0 3px rgba(0, 0, 0, 0.06);
}

.input-icon {
  color: #aaaaaa;
  flex-shrink: 0;
  margin-right: 10px;
  transition: color 0.25s ease;
}

.input-wrapper:focus-within .input-icon {
  color: #333333;
}

.input-wrapper input {
  flex: 1;
  border: none;
  outline: none;
  background: transparent;
  padding: 13px 0;
  font-size: 0.95rem;
  font-family: inherit;
  color: #111111;
}

.input-wrapper input::placeholder {
  color: #bbbbbb;
}

/* ===== Submit Button ===== */
.submit-btn {
  width: 100%;
  padding: 14px;
  background: #111111;
  color: #ffffff;
  border: none;
  border-radius: 10px;
  font-size: 1rem;
  font-weight: 600;
  font-family: inherit;
  cursor: pointer;
  transition: all 0.3s ease;
  letter-spacing: 0.3px;
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 50px;
}

.submit-btn:hover {
  background: #2a2a2a;
  transform: translateY(-1px);
  box-shadow: 0 6px 20px rgba(0, 0, 0, 0.2);
}

.submit-btn:active {
  transform: translateY(0);
  box-shadow: none;
}

.submit-btn--loading {
  pointer-events: none;
  opacity: 0.85;
}

/* ===== Spinner ===== */
.spinner {
  width: 20px;
  height: 20px;
  border: 2px solid rgba(255, 255, 255, 0.3);
  border-top-color: #ffffff;
  border-radius: 50%;
  animation: spin 0.7s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

/* ===== Footer ===== */
.form-footer {
  text-align: center;
  margin-top: 28px;
}

.form-footer p {
  font-size: 0.88rem;
  color: #999999;
  margin: 0;
}

.login-link {
  color: #111111;
  font-weight: 600;
  text-decoration: none;
  transition: opacity 0.2s ease;
}

.login-link:hover {
  opacity: 0.7;
  text-decoration: underline;
}

/* ===== Responsive: Tablet ===== */
@media (max-width: 900px) {
  .forgot-page {
    flex-direction: column;
  }

  .forgot-branding {
    padding: 40px 32px;
    min-height: auto;
  }

  .branding-title {
    font-size: 2.2rem;
  }

  .branding-description {
    display: none;
  }

  .branding-lines {
    margin-bottom: 0;
  }

  .forgot-form-panel {
    padding: 40px 32px;
  }

  .forgot-form-container {
    max-width: 420px;
  }
}

/* ===== Responsive: Mobile ===== */
@media (max-width: 600px) {
  .forgot-branding {
    padding: 32px 24px;
  }

  .branding-title {
    font-size: 1.8rem;
  }

  .branding-tagline {
    font-size: 0.88rem;
    margin-bottom: 16px;
  }

  .branding-lines {
    display: none;
  }

  .forgot-form-panel {
    padding: 32px 20px;
  }

  .form-title {
    font-size: 1.5rem;
  }

  .submit-btn {
    padding: 13px;
  }
}
</style>
