<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'

const router = useRouter()
const email = ref('')
const password = ref('')
const showPassword = ref(false)
const isLoading = ref(false)

function togglePassword() {
  showPassword.value = !showPassword.value
}

function handleSubmit() {
  if (!email.value || !password.value) return
  isLoading.value = true
  // Simulate API call then navigate
  setTimeout(() => {
    isLoading.value = false
    router.push('/generator')
  }, 1500)
}

function handleForgotPassword() {
  // Navigate to forgot password flow
  console.log('Forgot password for:', email.value)
}
</script>

<template>
  <section class="login-page">
    <!-- Left Panel: Branding -->
    <div class="login-branding">
      <!-- Decorative Markdown Watermark -->
      <div class="md-watermark" aria-hidden="true">
        <pre class="md-text">
# llms.txt

> A proposal to standardize
> how websites communicate
> with large language models.

## Overview

llms.txt is a file that
provides structured info
about your site for LLMs.

## Usage

```bash
$ llms-gen https://example.com
```

### Output Format

- title: Site Name
- description: A brief...
- sections:
  - /docs
  - /api
  - /blog

## Why llms.txt?

AI models need structured,
curated content to provide
accurate, helpful responses.

---

```markdown
# Example Output
> Generated by llms.txt
> generator v1.0
```

## Getting Started

1. Enter your site URL
2. Configure options
3. Generate your file
4. Deploy to your root

---

© 2026 llms.txt generator
        </pre>
      </div>

      <div class="branding-content">
        <h1 class="branding-title">
          LLMS.txt <span class="branding-accent">generator</span>
        </h1>
        <p class="branding-tagline">Generate text using LLMs</p>

        <!-- Decorative lines -->
        <div class="branding-lines">
          <div class="b-line"></div>
          <div class="b-line"></div>
          <div class="b-line"></div>
        </div>

        <p class="branding-description">
          Sign in to start generating structured<br />
          llms.txt files for your sites.
        </p>
      </div>
    </div>

    <!-- Right Panel: Login Form -->
    <div class="login-form-panel">
      <div class="login-form-container">
        <div class="form-header">
          <h2 class="form-title">Welcome back</h2>
          <p class="form-subtitle">Sign in to your account</p>
        </div>

        <form class="login-form" @submit.prevent="handleSubmit">
          <!-- Email Field -->
          <div class="input-group">
            <label class="input-label" for="login-email">Email</label>
            <div class="input-wrapper">
              <svg class="input-icon" width="18" height="18" viewBox="0 0 24 24" fill="none">
                <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M22 6l-10 7L2 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
              <input
                id="login-email"
                v-model="email"
                type="email"
                placeholder="you@example.com"
                required
                autocomplete="email"
              />
            </div>
          </div>

          <!-- Password Field -->
          <div class="input-group">
            <label class="input-label" for="login-password">Password</label>
            <div class="input-wrapper">
              <svg class="input-icon" width="18" height="18" viewBox="0 0 24 24" fill="none">
                <rect x="3" y="11" width="18" height="11" rx="2" ry="2" stroke="currentColor" stroke-width="1.5"/>
                <path d="M7 11V7a5 5 0 0110 0v4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
              </svg>
              <input
                id="login-password"
                v-model="password"
                :type="showPassword ? 'text' : 'password'"
                placeholder="Enter your password"
                required
                autocomplete="current-password"
              />
              <button
                type="button"
                class="password-toggle"
                @click="togglePassword"
                :aria-label="showPassword ? 'Hide password' : 'Show password'"
              >
                <!-- Eye open -->
                <svg v-if="!showPassword" width="18" height="18" viewBox="0 0 24 24" fill="none">
                  <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" stroke="currentColor" stroke-width="1.5"/>
                  <circle cx="12" cy="12" r="3" stroke="currentColor" stroke-width="1.5"/>
                </svg>
                <!-- Eye closed -->
                <svg v-else width="18" height="18" viewBox="0 0 24 24" fill="none">
                  <path d="M17.94 17.94A10.07 10.07 0 0112 20c-7 0-11-8-11-8a18.45 18.45 0 015.06-5.94M9.9 4.24A9.12 9.12 0 0112 4c7 0 11 8 11 8a18.5 18.5 0 01-2.16 3.19m-6.72-1.07a3 3 0 11-4.24-4.24" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
                  <line x1="1" y1="1" x2="23" y2="23" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
                </svg>
              </button>
            </div>
          </div>

          <!-- Forgot Password -->
          <div class="form-options">
            <button
              type="button"
              class="forgot-link"
              @click="handleForgotPassword"
            >
              Forgot password?
            </button>
          </div>

          <!-- Submit Button -->
          <button
            type="submit"
            class="submit-btn"
            :class="{ 'submit-btn--loading': isLoading }"
            :disabled="isLoading"
          >
            <span v-if="!isLoading">Sign in</span>
            <span v-else class="spinner"></span>
          </button>
        </form>

        <div class="form-footer">
          <p>Don't have an account? <a href="#" class="signup-link">Create one</a></p>
        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>
/* ===== Page Layout ===== */
.login-page {
  min-height: 100vh;
  display: flex;
  font-family: 'Inter', 'Segoe UI', sans-serif;
}

/* ===== Left Branding Panel ===== */
.login-branding {
  flex: 1;
  background: #000000;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 48px;
  position: relative;
  overflow: hidden;
}

/* Subtle diagonal texture */
.login-branding::before {
  content: '';
  position: absolute;
  top: -50%;
  right: -30%;
  width: 80%;
  height: 200%;
  background: linear-gradient(
    135deg,
    rgba(255, 255, 255, 0.02) 0%,
    rgba(255, 255, 255, 0.05) 50%,
    transparent 100%
  );
  transform: rotate(-12deg);
  pointer-events: none;
}

/* ===== Markdown Watermark Overlay ===== */
.md-watermark {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 0;
  pointer-events: none;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
}

.md-text {
  font-family: 'SF Mono', 'Fira Code', 'Cascadia Code', 'Consolas', monospace;
  font-size: 0.72rem;
  line-height: 1.8;
  color: rgba(255, 255, 255, 0.12);
  white-space: pre;
  margin: 0;
  padding: 40px;
  transform: rotate(-4deg) scale(1.15);
  user-select: none;
  letter-spacing: 0.3px;
  animation:
    md-drift 25s ease-in-out infinite alternate,
    md-pulse 8s ease-in-out infinite;
}

@keyframes md-drift {
  0% {
    transform: rotate(-4deg) scale(1.15) translateY(0px);
  }
  100% {
    transform: rotate(-4deg) scale(1.15) translateY(-30px);
  }
}

@keyframes md-pulse {
  0%, 100% {
    opacity: 0.5;
  }
  30% {
    opacity: 1;
  }
  60% {
    opacity: 0.35;
  }
  80% {
    opacity: 0.9;
  }
}

.branding-content {
  position: relative;
  z-index: 1;
  max-width: 400px;
}

.branding-title {
  font-size: 2.8rem;
  font-weight: 300;
  color: #ffffff;
  letter-spacing: -0.5px;
  margin: 0 0 8px 0;
}

.branding-accent {
  font-weight: 700;
  font-style: italic;
}

.branding-tagline {
  font-size: 1rem;
  font-style: italic;
  color: rgba(255, 255, 255, 0.5);
  margin: 0 0 32px 0;
}

.branding-lines {
  display: flex;
  flex-direction: column;
  gap: 10px;
  margin-bottom: 28px;
}

.b-line {
  height: 1px;
  background: linear-gradient(
    90deg,
    rgba(255, 255, 255, 0.25) 0%,
    rgba(255, 255, 255, 0.08) 100%
  );
}

.b-line:nth-child(1) { width: 100%; }
.b-line:nth-child(2) { width: 75%; }
.b-line:nth-child(3) { width: 50%; }

.branding-description {
  font-size: 0.95rem;
  color: rgba(255, 255, 255, 0.45);
  line-height: 1.7;
  margin: 0;
}

/* ===== Right Form Panel ===== */
.login-form-panel {
  flex: 1;
  background: #ffffff;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 48px;
}

.login-form-container {
  width: 100%;
  max-width: 380px;
}

/* ===== Form Header ===== */
.form-header {
  margin-bottom: 36px;
}

.form-title {
  font-size: 1.75rem;
  font-weight: 700;
  color: #111111;
  margin: 0 0 6px 0;
}

.form-subtitle {
  font-size: 0.95rem;
  color: #888888;
  margin: 0;
}

/* ===== Form ===== */
.login-form {
  display: flex;
  flex-direction: column;
  gap: 22px;
}

/* ===== Input Group ===== */
.input-group {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.input-label {
  font-size: 0.85rem;
  font-weight: 600;
  color: #333333;
  letter-spacing: 0.2px;
}

.input-wrapper {
  display: flex;
  align-items: center;
  border: 1px solid #e0e0e0;
  border-radius: 10px;
  padding: 0 14px;
  background: #fafafa;
  transition: all 0.25s ease;
}

.input-wrapper:focus-within {
  border-color: #111111;
  background: #ffffff;
  box-shadow: 0 0 0 3px rgba(0, 0, 0, 0.06);
}

.input-icon {
  color: #aaaaaa;
  flex-shrink: 0;
  margin-right: 10px;
  transition: color 0.25s ease;
}

.input-wrapper:focus-within .input-icon {
  color: #333333;
}

.input-wrapper input {
  flex: 1;
  border: none;
  outline: none;
  background: transparent;
  padding: 13px 0;
  font-size: 0.95rem;
  font-family: inherit;
  color: #111111;
}

.input-wrapper input::placeholder {
  color: #bbbbbb;
}

/* ===== Password Toggle ===== */
.password-toggle {
  background: none;
  border: none;
  cursor: pointer;
  color: #aaaaaa;
  padding: 4px;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: color 0.25s ease;
  outline: none;
}

.password-toggle:hover {
  color: #333333;
}

/* ===== Forgot Password ===== */
.form-options {
  display: flex;
  justify-content: flex-end;
  margin-top: -8px;
}

.forgot-link {
  background: none;
  border: none;
  font-size: 0.85rem;
  color: #888888;
  cursor: pointer;
  font-family: inherit;
  padding: 0;
  transition: color 0.2s ease;
}

.forgot-link:hover {
  color: #111111;
  text-decoration: underline;
}

/* ===== Submit Button ===== */
.submit-btn {
  width: 100%;
  padding: 14px;
  background: #111111;
  color: #ffffff;
  border: none;
  border-radius: 10px;
  font-size: 1rem;
  font-weight: 600;
  font-family: inherit;
  cursor: pointer;
  transition: all 0.3s ease;
  letter-spacing: 0.3px;
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 50px;
}

.submit-btn:hover {
  background: #2a2a2a;
  transform: translateY(-1px);
  box-shadow: 0 6px 20px rgba(0, 0, 0, 0.2);
}

.submit-btn:active {
  transform: translateY(0);
  box-shadow: none;
}

.submit-btn--loading {
  pointer-events: none;
  opacity: 0.85;
}

/* ===== Spinner ===== */
.spinner {
  width: 20px;
  height: 20px;
  border: 2px solid rgba(255, 255, 255, 0.3);
  border-top-color: #ffffff;
  border-radius: 50%;
  animation: spin 0.7s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

/* ===== Footer ===== */
.form-footer {
  text-align: center;
  margin-top: 28px;
}

.form-footer p {
  font-size: 0.88rem;
  color: #999999;
  margin: 0;
}

.signup-link {
  color: #111111;
  font-weight: 600;
  text-decoration: none;
  transition: opacity 0.2s ease;
}

.signup-link:hover {
  opacity: 0.7;
  text-decoration: underline;
}

/* ===== Responsive: Tablet ===== */
@media (max-width: 900px) {
  .login-page {
    flex-direction: column;
  }

  .login-branding {
    padding: 40px 32px;
    min-height: auto;
  }

  .branding-title {
    font-size: 2.2rem;
  }

  .branding-description {
    display: none;
  }

  .branding-lines {
    margin-bottom: 0;
  }

  .login-form-panel {
    padding: 40px 32px;
  }

  .login-form-container {
    max-width: 420px;
  }
}

/* ===== Responsive: Mobile ===== */
@media (max-width: 600px) {
  .login-branding {
    padding: 32px 24px;
  }

  .branding-title {
    font-size: 1.8rem;
  }

  .branding-tagline {
    font-size: 0.88rem;
    margin-bottom: 16px;
  }

  .branding-lines {
    display: none;
  }

  .login-form-panel {
    padding: 32px 20px;
  }

  .form-title {
    font-size: 1.5rem;
  }

  .submit-btn {
    padding: 13px;
  }
}
</style>
